// Localization dictionaries for Sabor Poshti Shop (Bangla / English)

export type LangType = 'bn' | 'en';

export const translations = {
  bn: {
    appName: 'সাব্বির পুষ্টি দোকান',
    address: 'হাজীগঞ্জ বাজার, চাঁদপুর',
    changeInfo: 'দোকানের তথ্য পরিবর্তন করুন',
    shopName: 'দোকানের নাম *',
    shopAddress: 'ঠিকানা / মোবাইল / বিবরণ *',
    cancel: 'বাতিল করুন',
    save: 'সংরক্ষণ করুন',
    cloudSyncing: 'সিঙ্ক হচ্ছে',
    cloudActive: 'ক্লাউড সচল',
    localDrive: 'লোকাল ড্রাইভ',
    dashboard: 'ড্যাশবোর্ড',
    newSale: 'নতুন বিক্রি',
    products: 'পণ্য ও মজুদ',
    customers: 'ক্রেতা তালিকা',
    transactions: 'লেনদেন জাবেদা',
    dateFilter: 'নির্দিষ্ট দিনের হিসাবপত্র ফিল্টার করুন:',
    allTimeFilter: 'আজকের দিনের চলমান হিসাব (কোনো নির্দিষ্ট ফিল্টার নেই)',
    clearFilter: 'ফিল্টার মুছুন',
    eggInventoryTitle: 'ডিম ইনভেন্টরি',
    addStock: 'মজুদ বৃদ্ধি',
    currentStock: 'বর্তমান মজুদ',
    ratePerUnit: 'বর্তমান দর',
    editPrice: 'দাম পরিবর্তন',
    successMsg: 'তথ্য সফলভাবে পরিবর্তন করা হয়েছে!',
    cancelBtn: 'বাতিল',
    confirmBtn: 'নিশ্চিত',
    languageLabel: 'ভাষা নির্বাচন (Select Language)',
    bengali: 'বাঙালী (Bangla)',
    english: 'ইন্টারন্যাশনাল (English)',
    profitTitle: 'আজকের সম্ভাব্য লাভ-ক্ষতি',
    dueCollected: 'বকেয়া আদায় ক্যাশ',
    totalSale: 'মোট বেচাকেনা',
    cashInHand: 'আজকের ক্যাশ-ইন-হ্যান্ড',
    dueTitle: 'আজকের মোট বকেয়া',
    dueLabel: 'মোট বকেয়া',
    transactionReceipt: 'রসিদ',
    sellPrompt: 'নতুন বিক্রি রশিদ তৈরি করুন',
    addStockPrompt: 'নতুন পণ্য যোগ করুন',
    quickSummary: 'সংক্ষিপ্ত সারসংক্ষেপ',
    searchCust: 'ক্রেতার নাম বা ফোন দিয়ে খুঁজুন...',
    addCust: 'নতুন ক্রেতা যোগ করুন',
    custPhone: 'ক্রেতার মোবাইল নং',
    custDue: 'ক্রেতার বকেয়া',
    actions: 'অ্যাকশন',
    noCust: 'কোনো ক্রেতা পাওয়া যায়নি।',
    customerDuesTitle: 'বকেয়া খাতা',
    totalDuesInStore: 'দোকানের সর্বমোট পাওনা বকেয়া'
  },
  en: {
    appName: 'Sabbir Nutrition Shop',
    address: 'Hajiganj Bazar, Chandpur',
    changeInfo: 'Change Shop Settings',
    shopName: 'Shop Name *',
    shopAddress: 'Address / Phone / Info *',
    cancel: 'Cancel',
    save: 'Save Changes',
    cloudSyncing: 'Syncing',
    cloudActive: 'Cloud Active',
    localDrive: 'Local Drive',
    dashboard: 'Dashboard',
    newSale: 'New Sale',
    products: 'Products & Stock',
    customers: 'Customer List',
    transactions: 'Transaction Ledger',
    dateFilter: 'Filter books by date:',
    allTimeFilter: 'Today\'s running ledger (No date filter applied)',
    clearFilter: 'Reset Filter',
    eggInventoryTitle: 'Egg Inventory Status',
    addStock: 'Add Stock',
    currentStock: 'Available Stock',
    ratePerUnit: 'Current Price',
    editPrice: 'Update Price',
    successMsg: 'Settings updated successfully!',
    cancelBtn: 'Cancel',
    confirmBtn: 'Confirm',
    languageLabel: 'Language Settings',
    bengali: 'বাংলা (Bangla)',
    english: 'English',
    profitTitle: 'Estimated Net Realized Margin',
    dueCollected: 'Due Debt Collected',
    totalSale: 'Gross Turnover Today',
    cashInHand: 'Cash in Drawer (All)',
    dueTitle: 'Total Outstanding Receivables',
    dueLabel: 'Active Due Outstanding',
    transactionReceipt: 'Receipt Details',
    sellPrompt: 'Create New Sale Receipt',
    addStockPrompt: 'Initialize New Custom Product',
    quickSummary: 'Snapshot Performance Metrics',
    searchCust: 'Search clients name/phone...',
    addCust: 'Register New Customer',
    custPhone: 'Phone Number',
    custDue: 'Outstanding Debt Due',
    actions: 'Actions',
    noCust: 'No active customer profiles found.',
    customerDuesTitle: 'Accounts Receivable',
    totalDuesInStore: 'Total Receivables Outstanding'
  }
};

export const getLang = (): LangType => {
  const saved = localStorage.getItem('sabbir_shop_lang');
  return (saved === 'en' ? 'en' : 'bn') as LangType;
};

export const setLang = (lang: LangType) => {
  localStorage.setItem('sabbir_shop_lang', lang);
};
